### ISSUE TITLE
Update user profile error ("Oops, something went wrong!")

### ISSUE THREAD

**Issue by sekafi** [creativetimofficial/ct-vue-material-dashboard-laravel-pro#10]
# Version

The current latest version downloaded a few days ago

# Current Behavior

When I change my user profile details and click UPDATE, I get the message "Oops, something went wrong!". What could be wrong ?

![vue_update_profile_error](https://user-images.githubusercontent.com/67909670/130924196-c65e8f9e-95b1-4e8a-890b-cac61ade5d84.jpg)

Updating and adding roles, categories and tags is ok

# Context

* Device: PC
* Operating System: Windows 10
* Browser and Version: Chrome 92.0.4515.159 /

**Comment by teamupdivision** [comment]
Hi @sekafi,

We are back with a few more details on this. It looks like the error is caused by the following:

APP_URL variable from api .env file should contain the URL of your Laravel JSON: API Project (eg. http://laravel-json-api-v2.test). The error means that the path is not correct.

Please let u know if this helped or there are some other specific details we should add. 
 
Best,
UPDIVISION Team

**Comment by sekafi** [comment]
Thank you. It helped.

**Comment by teamupdivision** [comment]
Hi @sekafi,

Thank you very much for the update. We're glad to hear that. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
