### ISSUE TITLE
Updating User Images fails with Error

### ISSUE THREAD

**Issue by krebbi** [creativetimofficial/ct-vue-material-dashboard-laravel-pro#4]
When I try to update a users profile image i get this response:

`{
"errors": [
{
"status": "422",
"title": "Unprocessable Entity",
"detail": "The profile image format is invalid.",
"source": {
"pointer": "/data/attributes/profile_image"
}
}
]
}`

**Comment by teamupdivision** [comment]
Hi there,

Thank you for using Creative-Tim Products!

In order to assist you, we'll need more details. 
Can you give us the image you try to update and let us know for what type of user you are trying to do the update?

Looking forward to hearing from you!

Thank you,

Updivision

**Comment by krebbi** [comment]
Attached the image.

Payload:
`{
"data": {
"id": "1",
"type": "users",
"attributes": {
"name": "Admin",
"email": "admin@material.com",
"profile_image": "/storage/users/1/profile-image/29np4X3lkAl9tMmLYS2iVU7LhTKMyiCqsIybBinH.jpeg",
"created_at": "2020-11-03 10:14:00",
"updated_at": "2020-11-03 10:14:00",
"links": {
"self": "http://api.xxxxxxx.loc/api/v1/users/1"
}
},
"relationships": {
"roles": {
"data": [
{
"id": "1",
"type": "roles"
}
]
}
}
}
}`

Response:

`{
"errors": [
{
"status": "422",
"title": "Unprocessable Entity",
"detail": "The profile image format is invalid.",
"source": {
"pointer": "/data/attributes/profile_image"
}
}
]
}`


![laravel-signet](https://user-images.githubusercontent.com/3884521/98246504-a9c62500-1f72-11eb-943b-5b7d508999f3.jpg)

**Comment by teamupdivision** [comment]
Hi,

We investigated what you sent.

The endpoint where the image is uploaded does not respond with a valid URL.
/storage/users/1/profile-image/29np4X3lkAl9tMmLYS2iVU7LhTKMyiCqsIybBinH.jpeg - this is not a valid URL, this is why when you try to assign the URL to a user via the user update endpoint - the user-update endpoint validates the payload and identifies the URL as being not valid, thus you get the error displayed.

We believe the problem is - in .env the URL is not right in APP_URL, in the backend, there is no symlink between the public and storage directory (This situation can be solved by with the **php artisan storage:link** command). In the backend, in .env the FILESYSTEM_DRIVER=public is missing.

Thank you,

Updivision

**Comment by krebbi** [comment]
FILESYSTEM_DRIVER=public

did the trick. thanks guys! 👍🏻

(it's not in the .env example....)

**Comment by teamupdivision** [comment]
Hey,

We are glad we could help you!

If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

Thank you,

UPDIVISION
